name: groq_sdk
description: A Dart client for interacting with the GroqCloud API
version: 0.0.1
repository: https://github.com/oriventi/groq-dart-sdk

library: groq_sdk.dart

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
